services:
  backend:
    container_name: backend
    build:
      context: ./backend
      target: prod
    environment:
      PORT: ${PORT:-3500}
      HOST: ${HOST:-0.0.0.0}
      FRONTEND_URL: ${FRONTEND_URL:-https://dblccinetech.fr}
      BASE_URL: ${BASE_URL:-https://api.themoviedb.org/3}
      API_TOKEN_FILE: /run/secrets/api_token
      JWT_TOKEN_FILE: /run/secrets/jwt_token
      JWT_EXPIRATION: ${JWT_EXPIRATION:-7d}
    secrets:
      - api_token
      - jwt_token
    expose:
      - "3500"
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: dev
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:1.27-alpine
    ports:
      - "${WEB_PORT}:80"
      - "${WEB_SSL_PORT:-443}:443"
    volumes:
      - ./frontend/nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./SSL:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend

secrets:
  api_token:
    file: ./secrets/api_token
  jwt_token:
    file: ./secrets/jwt_token
