services:
  backend:
    build:
      context: ./backend
      target: prod
    env_file:
      - ./.env
    expose:
      - "3500"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "${WEB_PORT:-8080}:80"
    depends_on:
      - backend
    restart: unless-stopped
